jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      arch: amd64
      script:
        - python hello_world.py
    - os: linux
      dist: xenial
      language: ruby
      cache: bundler
      arch: amd64
      script:
        - python hello_world.py
    
