jobs:
  include:
#     - os: windows
#       language: c
#       arch: amd64
#       script:
#         - clang -coverage -O0 hello_world.c -o hello_world
#         - ./hello_world
    - os: linux
      language: python
      dist: bionic
      arch: amd64
      script:
        - python hello_world.py
    
